const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('lumenAPI', {
  getKnowledgeBasePath: () => ipcRenderer.invoke('get-knowledge-base-path'),
  getDefaultKnowledgeBasePath: () => ipcRenderer.invoke('get-default-knowledge-base-path'),
  chooseKnowledgeBasePath: () => ipcRenderer.invoke('choose-knowledge-base-path'),
  ensureKnowledgeBase: () => ipcRenderer.invoke('ensure-knowledge-base'),
  readFile: (filePath) => ipcRenderer.invoke('read-file', filePath),
  writeFile: (filePath, content) => ipcRenderer.invoke('write-file', filePath, content),
  listProjects: () => ipcRenderer.invoke('list-projects'),
  listNotes: (projectName) => ipcRenderer.invoke('list-notes', projectName),
  createProject: (name) => ipcRenderer.invoke('create-project', name),
  createNote: (projectName, noteName, initialContent) => ipcRenderer.invoke('create-note', projectName, noteName, initialContent),
  deleteProject: (name) => ipcRenderer.invoke('delete-project', name),
  deleteNote: (projectName, noteName) => ipcRenderer.invoke('delete-note', projectName, noteName),
  renameProject: (oldName, newName) => ipcRenderer.invoke('rename-project', oldName, newName),
  renameNote: (projectName, oldNoteName, newNoteName) => ipcRenderer.invoke('rename-note', projectName, oldNoteName, newNoteName),
  exportProjectContent: (projectName) => ipcRenderer.invoke('export-project', projectName),
  exportNoteContent: (projectName, noteName, content) => ipcRenderer.invoke('export-note-content', projectName, noteName, content),
  insertAttachments: (projectName, noteName, kind, paths) => ipcRenderer.invoke('insert-attachments', projectName, noteName, kind, paths),
  exportNoteAssets: (projectName, noteName, targetFilePath) => ipcRenderer.invoke('export-note-assets', projectName, noteName, targetFilePath),
  openAttachment: (projectName, noteName, relPath) => ipcRenderer.invoke('open-attachment', projectName, noteName, relPath),
  showSaveDialog: (defaultPath, filters) => ipcRenderer.invoke('show-save-dialog', defaultPath, filters),
  writeExportFile: (filePath, content) => ipcRenderer.invoke('write-export-file', filePath, content),
  ensureInbox: () => ipcRenderer.invoke('ensure-inbox'),
  appendToNote: (projectName, noteName, content) => ipcRenderer.invoke('append-to-note', projectName, noteName, content),
  getAllNotesForLink: () => ipcRenderer.invoke('get-all-notes-for-link'),
  resolveNotePath: (projectName, noteName) => ipcRenderer.invoke('resolve-note-path', projectName, noteName),
  getInboxPath: () => ipcRenderer.invoke('get-inbox-path'),
  listInboxDays: () => ipcRenderer.invoke('list-inbox-days'),
  readInboxDay: (dateStr) => ipcRenderer.invoke('read-inbox-day', dateStr),
  writeInboxDay: (dateStr, content) => ipcRenderer.invoke('write-inbox-day', dateStr, content),
  fileExists: (filePath) => ipcRenderer.invoke('file-exists', filePath),
  noteExists: (projectName, noteName) => ipcRenderer.invoke('note-exists', projectName, noteName),
  moveToNote: (projectName, noteName, contentToAppend, inboxContentToReplace, inboxDateStr) =>
    ipcRenderer.invoke('move-to-note', projectName, noteName, contentToAppend, inboxContentToReplace, inboxDateStr),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  getUninstallerPath: () => ipcRenderer.invoke('get-uninstaller-path'),
  openUninstaller: () => ipcRenderer.invoke('open-uninstaller'),
  isPackaged: () => ipcRenderer.invoke('is-packaged'),
  windowMinimize: () => ipcRenderer.send('window-minimize'),
  windowMaximize: () => ipcRenderer.send('window-maximize'),
  windowClose: () => ipcRenderer.send('window-close'),
  windowIsMaximized: () => ipcRenderer.invoke('window-is-maximized'),
});
